apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  USER: {{ .Values.secret.user }}
  PASSWORD: "{{ .Values.secret.pass }}"
  BOT: {{ .Values.secret.bot }}
  DATABASE: {{ .Values.secret.db }}
  HOST: {{ .Values.secret.host }}