name: initial_installation

on:
  push:
    tags:
      - 'v.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo pass
        env:
          PASSFORSECRET: ${{ secrets.PASSFORSECRET }}
        run: $PASSFORSECRET > password

      - name: run playbook replacing-variables.yml 
        run: ansible-playbook --extra-vars="@secretbot.yml" --vault-password-file password replacing-variables.yml

      - name: run playbook replacing-variables.yml 
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i inventory.yml --extra-vars "@vars.yml" initial_installation.yml -u foilv

          
